name: Blazor Toolkit Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types:
    - published

env:
  project: src/AstroPanda.Blazor.Toolkit.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 🏥 Restore dependencies
      run: dotnet restore ${{ env.project }}
    
    - name: 🛠 Build
      run: dotnet build ${{ env.project }} --no-restore
    
    - name: 🧪 Test
      run: dotnet test ${{ env.project }} --no-build --verbosity normal
      
    - name: 📦 Package
      if: github.event_name == 'release'
      run: dotnet pack ${{ env.project }} --no-build -p:Version=${{ github.ref_name }} --output "${{ runner.temp }}"

    - name: Publish to GitHub Packages
      if: github.event_name == 'release'
      run: |-        
        dotnet nuget push ${{ runner.temp }}/*.nupkg -s github

    - name: Publish to NuGet
      if: github.event_name == 'release' && always()
      run: |-        
        dotnet nuget push ${{ runner.temp }}/*.nupkg -k ${{ secrets.NUGET_PUBLIC_API_KEY }} -s https://api.nuget.org/v3/index.json  
